In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
a= np.array(['1','2','numpy'])

In [5]:
print(a)

['1' '2' 'numpy']


In [6]:
x= [1,2,'3']

In [7]:
c = np.array(x)

In [8]:
print(c)

['1' '2' '3']


In [14]:
a = np.zeros(6)

In [15]:
print(a)

[0. 0. 0. 0. 0. 0.]


In [16]:
empty = np.empty(6)
print(empty)

[0. 0. 0. 0. 0. 0.]


In [17]:
arange = np.arange(6)
print(empty)

[0. 0. 0. 0. 0. 0.]


In [18]:
print(np.ndim(a))

1


In [21]:
arr = np.array([[1,2,3],[2,2,2]])


In [24]:
print(np.shape(arr))

(2, 3)


In [36]:
a= np.array([1,2,3,5,7])
w = np.arange(10)

In [37]:
print(w)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
data = np.array([2,3,4])

In [41]:
print(data)

[2 3 4]


In [45]:
print(data[1:])

[3 4]


In [58]:
var = np.array([1,4,3])
var1 = np.array([2,2,2])

In [59]:
print(np.multiply(var,var1))

[2 8 6]


In [60]:
y =  np.array([[1,2,4],[4,5,6]])

In [63]:
print(y)

[[1 2 4]
 [4 5 6]]
